@startuml Forge

package "Software Architecture" <<Rectangle>> {

  package "Main Application" <<Rectangle>> {
    class Main {
  
    }
    class Application {
  
    }
    class Editor {
  
    }
    class GUI {
  
    }
    class Simulation {
  
    }
    class Window {
  
    }
    class Panel {
  
    }
    class HierarchyPanel {
  
    }
    class ViewportPanel {
  
    }
    class Camera {
  
    }
    class Framebuffer {
  
    }
  }
  
  package "Renderer Utility" <<Rectangle>> {
    class BufferElement {
  
    }
    class BufferLayout {
  
    }
    class VertexBuffer {
  
    }
    class IndexBuffer {
  
    }
    class Renderer {
  
    }
    class Shader {
  
    }
    class VertexArray {
  
    }
  }
  
  package "General Utility" <<Rectangle>> {
    class Log {
          
    }
    class Safety {
  
    }
    class Timestep {
  
    }
    class MathUtils {
  
    }
    class StaticShaders {
  
    }
    class Input {
  
    }
  }
  
  package "Event System" <<Rectangle>> {
    class EventDispatcher {
  
    }
    class Event {
  
    }
    class MouseEvent {
  
    }
    class KeyEvent {
  
    }
    class ApplicationEvent {
  
    }
  }
}

package "Network Architecture" <<Rectangle>> {
  package "Central Controller Modal" <<Rectangle>> {
    class ControlNode {
    
    }
    class Worker1 {
    
    }
    class Worker2 {
    
    }
    class Worker3 {
    
    }
    class WorkerX {
    
    }
  }
}

Application-u->Main
Window-l->Application
GUI-r->Application
Editor-u->Application
Panel-r->Editor : *
Simulation-l->Editor
Camera-u->Editor
HierarchyPanel..r|>Panel
ViewportPanel..u|>Panel
Framebuffer-r->ViewportPanel

IndexBuffer-u->Renderer
VertexBuffer-u->Renderer
VertexArray-u->Renderer
Shader-u->Renderer
BufferElement-u->BufferLayout : *
BufferLayout-u->VertexBuffer
BufferLayout-u->IndexBuffer

Event-u->EventDispatcher
MouseEvent-u->Event
ApplicationEvent-u->Event
KeyEvent-u->Event

Worker1-u->ControlNode
ControlNode-d->Worker1
Worker2-u->ControlNode
ControlNode-d->Worker2
Worker3-u->ControlNode
ControlNode-d->Worker3
WorkerX-u->ControlNode
ControlNode-d->WorkerX

@enduml
